// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizASP.Model;

namespace QuizASP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200428161019_quizLetrehozasa")]
    partial class quizLetrehozasa
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuizASP.Model.quiz", b =>
                {
                    b.Property<int>("Kerdes_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Helyes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kerdes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valasz_A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valasz_B")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valasz_C")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valasz_D")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Kerdes_id");

                    b.ToTable("quiz");
                });
#pragma warning restore 612, 618
        }
    }
}
